services:
  db:
    image: postgres
    restart: always
    container_name: blog_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: 'Europe/Warsaw'
      POSTGRES_DB: blog_db
    ports:
        - 5432:5432
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
