services:
  db:
    image: postgres
    container_name: blog_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: 'Europe/Warsaw'
      POSTGRES_DB: blog_db
    ports:
        - 5432:5432
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    ports:
      - 8080:8080
